### ISSUE TITLE
Improve pop.html

### ISSUE THREAD

**Issue by narasimha-1511** [narasimha-1511/chrome-extension-for-auto-otp#1]
Improve the Html in pop.html in the repository..

**Comment by Panth1823** [comment]
Hey!! i can work on this @narasimha-1511

**Comment by narasimha-1511** [comment]
Go On @Panth1823  
Thanks From Showing Intrest

**Comment by Panth1823** [comment]
#2

**Comment by Panth1823** [comment]
fixed #2

**Comment by narasimha-1511** [comment]
hey Thank You @Panth1823 :confetti_ball:
